-- Read-only statement
SELECT OWNER, TABLE_NAME, NUM_COLS, NUM_ROWS FROM TAB_COL_ROW_COUNTS;

-- Drop table, if it exists
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TAB_COL_ROW_COUNTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Creates table from results of system tables
CREATE TABLE TAB_COL_ROW_COUNTS AS
SELECT t.OWNER, t.TABLE_NAME, c.NUM_COLS, r.NUM_ROWS
 FROM
   ALL_TABLES t,
   ALL_TAB_STATISTICS r,
   (SELECT s.OWNER, s.TABLE_NAME, COUNT(*) NUM_COLS
   FROM ALL_TAB_COLUMNS s
   GROUP BY s.OWNER, s.TABLE_NAME) c
 WHERE t.TABLE_NAME = r.TABLE_NAME
   AND t.TABLE_NAME = c.TABLE_NAME
   AND t.OWNER = r.OWNER
   AND t.OWNER = c.OWNER
   AND t.TABLESPACE_NAME = 'USERS'
   AND t.OWNER = 'HR'
 ORDER BY TABLE_NAME;