SELECT t.OWNER, t.TABLE_NAME, c.NUM_COLS, r.NUM_ROWS
FROM
  ALL_TABLES t,
  ALL_TAB_STATISTICS r,
  (SELECT s.OWNER, s.TABLE_NAME, COUNT(*) NUM_COLS
  FROM ALL_TAB_COLUMNS s
  GROUP BY s.OWNER, s.TABLE_NAME) c
WHERE t.TABLE_NAME = r.TABLE_NAME
  AND t.TABLE_NAME = c.TABLE_NAME
  AND t.OWNER = r.OWNER
  AND t.OWNER = c.OWNER
  AND t.TABLESPACE_NAME = “MY_TABLESPACE_NAME”
  AND t.OWNER = “MY_TABLE_OWNER”
ORDER BY TABLE_NAME;