CREATE TABLE TAB_COL_ROW_COUNTS
AS
SELECT t.TABLE_NAME, c.NUM_COLS, r.NUM_ROWS
FROM
  ALL_TABLES t,
  ALL_TAB_STATISTICS r,
  (SELECT s.TABLE_NAME, COUNT(*) NUM_COLS
  FROM ALL_TAB_COL_STATISTICS s
  GROUP BY s.TABLE_NAME) c
WHERE t.TABLE_NAME = r.TABLE_NAME
  AND t.TABLE_NAME = c.TABLE_NAME
  AND t.TABLESPACE_NAME = 'USERS'; -- Distinct TABLESPACE_NAME values are: SYSTEM, SYSAUX, USERS, (null)
  